[package]
name = "git_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["cargo", "derive"] }
flate2 = "1.1.2"
hex = "0.4.3"
sha1 = "0.10.6"
tempfile = "3.20.0"
thread_local = "1.1.9"

[dev-dependencies]
git2 = "0.20.2"
